//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubirDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_dashboard
    {
        public Nullable<System.DateTime> Fecha_Operacion { get; set; }
        public string Fecha_de_Presentacion { get; set; }
        public Nullable<System.DateTime> Fecha_de_Pago { get; set; }
        public string Nro__de_Cupon { get; set; }
        public Nullable<double> Nro__de_Comercio { get; set; }
        public Nullable<double> Nro__de_Tarjeta { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Total_Bruto { get; set; }
        public Nullable<decimal> Total_Descuento { get; set; }
        public Nullable<decimal> Total_Neto { get; set; }
        public string Entidad_Pagadora { get; set; }
        public string Cuenta_Bancaria { get; set; }
        public string Nro__Liquidacion { get; set; }
        public string Nro__de_Lote { get; set; }
        public string Tipo_de_Liquidacion { get; set; }
        public string Estado { get; set; }
        public Nullable<double> Cuotas { get; set; }
        public Nullable<double> Nro__de_Autorizacion { get; set; }
        public string Tarjeta { get; set; }
        public string Tipo_de_Operacion { get; set; }
        public string Comercio_Participante { get; set; }
        public string Promocion_Plan { get; set; }
        public string Tarjeta_Tipo { get; set; }
        public Nullable<double> Costo_Financiero { get; set; }
        public Nullable<decimal> Costo_Financiero_en__ { get; set; }
        public string Tipo_de_Financiacion { get; set; }
        public Nullable<decimal> Costo_por_anticipo { get; set; }
        public Nullable<double> C__Comision_con_IVA { get; set; }
        public Nullable<decimal> Arancel { get; set; }
        public Nullable<decimal> IVA_21_ { get; set; }
        public Nullable<decimal> IMPUESTO_DEBITO_CREDITO { get; set; }
        public Nullable<double> CUIT { get; set; }
        public string Condicion_Fiscal { get; set; }
        public string Provincia { get; set; }
        public Nullable<decimal> Retencion_Provincial { get; set; }
        public Nullable<decimal> Retencion_Ganacia { get; set; }
        public Nullable<decimal> Retencion_IVA { get; set; }
        public Nullable<decimal> Total_Con_descuentos { get; set; }
        public string CBU_CVU { get; set; }
        public string Banco { get; set; }
        public string Tipo_de_cuenta { get; set; }
        public string Nro_de_cuenta { get; set; }
        public string Alias { get; set; }
        public string Nombre_Comercio { get; set; }
        public Nullable<decimal> Retencion_Municipal { get; set; }
        public string RETENCION { get; set; }
        public Nullable<decimal> Retencion_impositiva { get; set; }
        public string Asesor_ABM { get; set; }
        public string Rubro { get; set; }
        public Nullable<double> Fecha_Alta_comercio { get; set; }
        public string Provincia_ABM { get; set; }
        public string Razon_Social { get; set; }
        public Nullable<double> Legajo { get; set; }
        public Nullable<double> Cod__Actividad { get; set; }
        public Nullable<int> Año_op { get; set; }
        public Nullable<int> Mes_op { get; set; }
        public Nullable<int> Año_Pago { get; set; }
        public Nullable<int> Mes_Pago { get; set; }
        public Nullable<int> semana_mes_pago { get; set; }
        public Nullable<int> semana_mes_op { get; set; }
        public string dia_semana { get; set; }
        public string TIPO_DE_CREDITO { get; set; }
        public string Tipo_Financiacion { get; set; }
        public Nullable<double> Codigo_Postal { get; set; }
        public Nullable<System.DateTime> Fecha_OP { get; set; }
        public Nullable<decimal> Arancel_Fiserv { get; set; }
        public string Pago_Real { get; set; }
        public Nullable<int> dias_habiles { get; set; }
        public Nullable<decimal> Formula_anticipo { get; set; }
        public string TASA_PREFERENCIAL { get; set; }
        public Nullable<System.DateTime> fecha_tasa_preferencial { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<double> ganancia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Debito_credito { get; set; }
        public Nullable<double> COD__ACTIVIDAD_RENTAS { get; set; }
        public string anticipo_ { get; set; }
        public string BONIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA2 { get; set; }
    }
}
