//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubirDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosPendientes
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
        public string MarcaTarjeta { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string NroTerminal { get; set; }
        public string Resultado { get; set; }
        public string Cuota { get; set; }
    }
}
